### ISSUE TITLE
Monitor Computer Members in a OU [Feature Request]

### ISSUE THREAD

**Issue by tjddx** [lazywinadmin/Monitor-ADGroupMembership#37] opened 2019-04-18 05:15 UTC
Hi
Is it possible to monitor the Computer member changes of a OU?
Thanks a lot.

**Comment by lazywinadmin** [comment] 2019-04-18 06:15
Hi, thanks for the feedback @tjddx 
duplicate of #29

**Closed by lazywinadmin** 2019-04-18 06:15 UTC
